version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:8.1.0
    container_name: kafkakf
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
        KAFKA_KRAFT_MODE: "true"
        KAFKA_PROCESS_ROLES: "broker,controller"
        KAFKA_NODE_ID: "1"
        KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
        KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
        KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
        KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
        KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
        KAFKA_CLUSTER_ID: "kraft-cluster-1"
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: logsdb
      MYSQL_USER: loguser
      MYSQL_PASSWORD: logpassword
    volumes:
      - mysql_data:/var/lib/mysql

  kafka-connect:
    image: confluentinc/cp-kafka-connect:8.1.0
    container_name: kafka-connect
    depends_on:
      - kafka
      - mysql
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: "connect-cluster"
      CONNECT_CONFIG_STORAGE_TOPIC: "connect-configs"
      CONNECT_OFFSET_STORAGE_TOPIC: "connect-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "connect-status"
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_REST_ADVERTISED_HOST_NAME: "localhost"
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/java/custom"
      CONNECT_JDBC_DRIVER_CLASS: "com.mysql.cj.jdbc.Driver"
      CONNECT_JDBC_URL: "jdbc:mysql://mysql:3306/logsdb?user=loguser&password=logpassword"
    volumes:
      - ./plugins:/usr/share/java/custom

volumes:
  mysql_data:
